kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - name: factorio
        image: dtandersen/factorio:0.16.51
        imagePullPolicy: Always
        ports:
        - containerPort: 27015
        readinessProbe: &default_probe
          tcpSocket:
            port: 27015
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe: *default_probe
        env:
          - name: APP
            value: factorio
        resources:
          requests:
            memory: "6000Mi"
            cpu: "4"
        volumeMounts:
        - mountPath: /factorio
          name: factorio-vl
      volumes:
      - name: factorio-vl
        persistentVolumeClaim:
          claimName: factorio-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pv-claim
  labels:
    app: factorio
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
---
kind: Service
apiVersion: v1
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  selector:
    app: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: 34197
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: 27015
